spring:
  application:
    name: zel-e-comm
  datasource:
    url: jdbc:postgresql://localhost:5432/ecomm
    username: zel
    password: cheese
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
project:
  path:
    images: ./images
jwt:
  expiration: 86400000
  secret: O94xB3Mg2ayT+SM+8ExVuN+obkkpntc7EwowKBPXFchlNPWY06ggerto53XC8q0H+G56YWrG9LAInLFfjBrKFA==
  cookie: access_token_z


