spring:
  application:
    name: zel-e-comm
  datasource:
    url: jdbc:postgresql://localhost:5432/ecomm
    username: zel
    password: cheese
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect